fix: Retirando módulo status do FastAPI
dunossauro/fastapi-do-zero pull request #129
Opened 2024-04-23 21:07 UTC by RWallan

Retirando o módulo `status` do FastAPI para padronizar para HTTPStatus do módulo http.

Dessa forma, o texto e os códigos ficam no padrão utilizado com o HTTPStatus.

closes #128

2024-05-06 06:32 UTC, dunossauro requested changes

2024-05-06 06:32 UTC, dunossauro commented on codigo_das_aulas/fast_zero/fast_zero/security.py
> +from datetime import datetime, timedelta
Esse arquivo deveria mesmo estar aqui?

2024-05-08 09:29 UTC, RWallan commented on codigo_das_aulas/fast_zero/fast_zero/security.py
> +from datetime import datetime, timedelta
Corrigido, @dunossauro

2024-05-08 09:31 UTC, RWallan commented on codigo_das_aulas/fast_zero/fast_zero/security.py
> +from datetime import datetime, timedelta
Resolvido, @dunossauro

2024-05-09 11:39 UTC, merged